version: '3.1'

services:
  web-selenium:
    image: tonyp7/flask-selenium-chromedriver-alpine:latest 
    container_name: flask-selenium-chromedriver-alpine
    shm_size: '2gb'
    build:
      context: . 
    ports:
      - 8000:8000
