version: '3.1'

services:
  server:
    image: tonyp7/flask-selenium-chromedriver:latest 
    container_name: flask-selenium-chromedriver
    shm_size: '2gb'
    build:
      context: . 
    ports:
      - 8000:8000
