name: Build 3.12

on: push
jobs:
  Debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build and run the project
        run: docker compose up --build -d
        working-directory: 3.12-slim
      - name: Test the endpoint
        run: docker run --network container:flask-selenium-chromedriver appropriate/curl --retry 10 http://localhost:8000/test
  Alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build and run the project
        run: docker compose up --build -d
        working-directory: 3.12-alpine
      - name: Test the endpoint
        run: docker run --network container:flask-selenium-chromedriver-alpine appropriate/curl --retry 10 http://localhost:8000/test
